### ISSUE TITLE
Pod versions in Podfile

### ISSUE THREAD

**Issue by skyylex** [seanoshea/BluePlaquesLondon#35]
I suggest to set specific version for each pod, rather than update to the latest (if no version specified)

**Comment by seanoshea** [comment]
See https://github.com/seanoshea/BluePlaquesLondon/pull/36. Is this what you had in mind?

**Comment by skyylex** [comment]
Yep. It's more stable way to deal with pods, in my practice update need to be done on demand.

**Comment by seanoshea** [comment]
OK - I'll close out the ticket then. Thanks for the prompt to do this.
