### ISSUE TITLE
If there is any Roadmap?

### ISSUE THREAD

**Issue by skyylex** [seanoshea/BluePlaquesLondon#37]
It would be useful for the development to have a vision of required features and improvements which are necessary for next or current release. So other developers can fully understand what they can do and how to help. From my point of view some kind of  Roadmap or TODO list will be enough for that purpose.

**Comment by seanoshea** [comment]
A great idea. I had a few ideas in my head, but it's probably useful to get them down into some sort of TODO list. Will publish something soon to the README.

**Comment by seanoshea** [comment]
Had a first stab at a road map wiki. Check it out at https://github.com/seanoshea/BluePlaquesLondon/wiki/Road-Map.
